### ISSUE TITLE
Is this project still under active development ??

### ISSUE THREAD

**Issue by hamza0867** [felipecsl/kales#46]
Hello.

I'm loving this project and would like to see it grow and get more attention. I believe it would be so useful for many people out there. I just want to know what are the plans for this project.

Thank you so much

**Comment by felipecsl** [comment]
Hello! Thanks for asking! This has been on hold for the past month or so as I've been busy with other stuff and also it didn't seem to initially pick up enough attention for me to think it was worth pursuing this idea.
I believe it would be super useful too (at least for me) but it's a big project that would need a community around it. If people are not excited/involved, then I don't really see a point of me doing this just for myself 😄 

I'll leave this issue open so other people can chime in if they feel excited about it. I'll try to find some time to work on it! :)

**Comment by hamza0867** [comment]
Hello @felipecsl , thank you for your response. I tried to search for kales, rails, kotlin on rails on [kotlin reddit](https://www.reddit.com/r/Kotlin/) and there wasn't any thread about kales. Maybe you can post a thread explaining the idea and the ambition to get more attention ??

**Comment by felipecsl** [comment]
thats a good idea, thanks! I'll definitely do that

**Comment by felipecsl** [comment]
done 😄 https://www.reddit.com/r/Kotlin/comments/c9873g/a_kotlin_web_development_mvc_framework/
