### ISSUE TITLE
Windows support (CLI Installation)

### ISSUE THREAD

**Issue by PraveenGandhi** [felipecsl/kales#55]
Would be nice if Windows support (CLI Installation) is there. Windows batch file might be required

![image](https://user-images.githubusercontent.com/1082966/60758522-456d1b80-a035-11e9-827c-611959f357f7.png)

**Comment by PraveenGandhi** [comment]
```kales new``` is failing with ```sh``` in windows

**Comment by felipecsl** [comment]
hmm I don't have a windows machine ready to test, would appreciate if you'd contribute a fix 🙏

**Comment by PraveenGandhi** [comment]
Ok, I think I can try to do ```kalesw```, similar to ```gradlew```, ```mvnw```. Let me your thoughts, so that work on it.

**Comment by felipecsl** [comment]
yep that's exactly what this script is for 😃  https://github.com/felipecsl/kales/blob/master/scripts/kales

**Comment by PraveenGandhi** [comment]
Ok, let me port it to ```.bat/.cmd``` 😃

**Comment by PraveenGandhi** [comment]
https://github.com/felipecsl/kales/pull/63

**Comment by felipecsl** [comment]
This should be fixed by #67
